### ISSUE TITLE
Integrate Data of SMA EV Charger

### ISSUE THREAD

**Issue by Hanni91** [iobroker-community-adapters/ioBroker.sma-em#116]
Is it possible to integrate the Data of the Electricity consumers, which are controlled by the EM (SHM2.0)?

What Information is necessary to integrate this topic?

Data over Webui of the EV Charger 22:
[Momentanwerte - My plant - 2021-01-20.txt](https://github.com/iobroker-community-adapters/ioBroker.sma-em/files/5842051/Momentanwerte.-.My.plant.-.2021-01-20.txt)

**Comment by pdbjjens** [comment]
@Hanni91 
The SMA-EM adapter is not the right adapter to access the data of the SMA EV-Charger, since it only can receive and decode datagrams which are multicast by the SEM or the SHM. The SMA EV-Charger does not include an own Energy Meter and thus does not multicast any measurement data like the SEM or the SHM. Rather it receives the measurement data f.i. for all data relating to the "Netzanschluss" which it displays it in its user interface  from the SHM. 
I am not familiar with the SMA EV-Charger but if it is accessible via modbusTCP like most other SMA devices (like f.i. the Sunny Island inverters), you will probably be able to access all the "Momentanwerte" information via  iobroker modbus adapter.
You can check if the SMA EV-Charger supports modbus by checking in its Web-UI (user: Installer) under "Geräteparameter/Externe Kommunikation" if there is an entry "Modbus"

 Last resort would be to pull the data from the Sunny Portal using the iobroker Sunny Portal adapter.

**Comment by pdbjjens** [comment]
@Hanni91 
After reading some documentation on the web, I believe that the SMA-EV charger does not support modbus access.
As explained before it also does not support the SMA-EM protocol. So it seems to me that the only way to access the SMA-EV-Charger data is via Sunny Portal or a totally new iobroker Adapter (or maybe an extension of the existing iobroker-speedwire adapter).
Can I close this issue or do you still have questions regarding the SMA-EM Adapter?

**Comment by pdbjjens** [comment]
@Hanni91 
Since I got no response from you, I assume that you do not have any further questions and thus close this issue.
