### ISSUE TITLE
Current Energy production

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.sma-em#120]
Hi,

do I see it correct, that there is no value for the current energy production in Watts?

I see current surplus (what I sell) and regard (what I buy) but not what I consume. And this value isn't calculatable as I don't see current production.

**Comment by pdbjjens** [comment]
Yes, you are right. The SEM or the SEM-part of the SHM only measure the power  flowing through it. But it can distiguish the direction of the energy flow. (regard means the energy flowing in, surplus is the energy flowing  out). What you measure thus depends on where your SEM is placed. If it is placed on the grid connection, you get the power received from the grid or fed into the grid. If you place it on the connection to your PV-Generator, you get the PV-production. For computing f.i. the Self- consumption you need to measure both, the production and the feed-in. Thus, besides the SHM you need either a second SEM (measuring the PV-production) or pull the PV-production value directly from the PV-inverters (for SMA-inverters this is easily done via modbus).

**Comment by maxpd1** [comment]
Thank you @pdbjjens for explanation
In my SunnyPortal hosted via SHM I see the missing values. So current consumption and current production. Therefore I wonder why they are not shown in iobroker

**Comment by pdbjjens** [comment]
@maxpd1 
This is so because afaik the SHM collects the production values from the PV-inverters using a SMA-specific network protocol (speedwire) and forwards it together with the received and feed-in power values to the Sunny Portal - again via a SMA-specific protocol. Sunny Portal then computes the various values for self-consumption and self-sufficiency from these measurements. Unfortunately the measurement values for PV-procuction from the SHM are not available locally because the SHM protocol is not disclosed. Also pulling the data from the Sunny Portal with f.i. with the iobroker sunny portal adapter is currently not possible, because SMA has changed something in the access control. Therefore my recommendation is that you collect the PV-production data from the SMA PV-inverters via the iobroker Modbus  adapter and compute the required values from that. Besides the production data the SMA PV-inverters also make the grid power (feed-in and received power as measured by the SHM-internal SEM) and many other data available via modbus. Thus you would only need the iobroker Modbus adapter to compute all the values you need. In the iobroker Forum there is a discussion group regarding the modbus adapter and also one specificially adressing SMA-inverters. If this explanation is sufficient for you, please close this issue. Of course feel free to ask any further questions.

**Comment by pdbjjens** [comment]
@maxpd1 
Can I close this issue or do you have further questions?

**Comment by maxpd1** [comment]
I thank you very much for your detailed explanation. I am now trying to get modbus running. We can close this one.
