### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by TJJochen** [iobroker-community-adapters/ioBroker.sma-em#13]
Is it also possible to include the datapoint of the mains frequency in the adapter? Thank you

**Comment by CTJaeger** [comment]
The Energy Meter does not support mains frequency. 
[https://www.sma.de/fileadmin/content/global/Partner/Documents/SMA_Labs/EMETER-Protokoll-TI-de-10.pdf](url)

**Comment by TJJochen** [comment]
The current model of the SMA EnergyMeter Type 20 apparently supports mains frequency. On the internal web interface, the frequency is always displayed under instantaneous values.

**Comment by CTJaeger** [comment]
I can not find documentation about the protocol anywhere. In the SMA developer area, only the eMeter10 protocol file exists. As soon as I have this new one, this feature will be implemented quickly. Unfortunately, I can not do independent testing because I do not have the new version of EnergyMeter.

**Comment by DutchmanNL** [comment]
please retest with new version
