### ISSUE TITLE
EV Charger Data

### ISSUE THREAD

**Issue by bobmorane77** [iobroker-community-adapters/ioBroker.sma-em#155]
Can you update the adapter, so that we can get valid data from the sma ev charger?
Right now the charger is recognized, but gets not all data obkects.

![sma-em-ev-charger](https://user-images.githubusercontent.com/12913409/113112608-a8d7ad80-9209-11eb-809c-b7edbbfd9d42.png)

**Comment by pdbjjens** [comment]
@bobmorane77 
To me it seems quite strange that the sma-em adapter detects a device called SMA EV Charger. This I can find nowhere in the code. Which version of the sma-em Adapter do you use?
Also I am not aware of  the SMA EV Charger using the SMA Energy Meter protocol. Therefore I think that the detection of such a device is due to a bug in the sma-em adapter which we are currently fixing.  However, if you have other information about the SMA EV charger protocol, please let us know.

**Comment by pdbjjens** [comment]
@bobmorane77 
If you would post an iobroker log of the start of the sma-em adapter instance and any subsequent error messages or warnings of the adapter I could take a closer look into what is happening.

**Comment by bobmorane77** [comment]
Hi,
the SMA EV Charger is the wallbox from SMA and the Adapter finds also the SerialNumber. I think thats not a bug. They communicate with the same protocol and are quite similiar devices
[log.txt](https://github.com/iobroker-community-adapters/ioBroker.sma-em/files/6262896/log.txt)
. 
In the log i don't see errors.

cu

**Comment by pdbjjens** [comment]
@bobmorane77 
Thank you for the log. It looks quite normal (except for the large number of eth interfaces ;-) ). My impression is that SMA has introduced a new protocol-ID over the speedwire multicast protocol (in addition to the sma-em and the speedwire device discovery protocols which I am currently aware of) especially for SMA EV Charger. Unfortunately afaik SMA has not disclosed this protocol. It will not be possible to decode these datagrams until the exact protocol structure is known (although it seems to be quite close to the sma-em protocol - at least in the header - otherwise the sma-em adapter would not have detected it)
To verify whether this is really some kind of new protocol would you do us a favour and install a test version of the sma-em directly from github https://github.com/TGuybrush/ioBroker.sma-em.git . This version checks the protocol-ID and only reacts on the sma-em protocol-id . Thus it should not detect the SMA-EV-Charger anymore. I know, this is not what you expect, but it would help to understand if this issue really depends on the protocol-id.

**Comment by bobmorane77** [comment]
OK
with a new instance it looks like logfile almost the same
but objects just the Homemanger

![screen](https://user-images.githubusercontent.com/12913409/113710480-0d9c7780-96e4-11eb-8562-24dea5fe2980.png)
[logs2.txt](https://github.com/iobroker-community-adapters/ioBroker.sma-em/files/6264595/logs2.txt)

To get data from the EV Charger would be better ;-)

**Comment by pdbjjens** [comment]
Did you uninstall the previous version of the sma-em and then install the version from github which i mentioned above? (I am asking because I am a bit confused why you have an instance called sma-em.1 This looks as if there is still the old sma-em.0 instance active in your system) Anyhow - if you instanciated the github version, it is just what it is expected to do - just find SMA Energy Meters or Sunny Home Managers - not SMA EV chargers. As I explained above, we can only implement the SMA EV charger if the protocol it uses is disclosed. Currently I am not aware of any public information about the SMA EV Charger protocol anywhere on the internet. If you get to know anything, you are welcome to share it with us. 
Also you could join the discussions on SMA on the iobroker forum https://forum.iobroker.net/topic/1100/sma-wechselrichter  or the test thread of sma-em 0.6.x https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-6-x-latest 
Maybe someone in the iobroker community knows more about the SMA EV Charger. 
I would like to close this issue here. But I am certainly willing to reopen it as a feature request when we get more information on the protocol which allows an implementation.
