### ISSUE TITLE
EV Charger without SHM

### ISSUE THREAD

**Issue by lolax80** [iobroker-community-adapters/ioBroker.sma-em#162]
Hello,

is it possible to read objects from the Sma ev charger without the Sunny Home Manager?

**Comment by pdbjjens** [comment]
@lolax80 
Which data objects are you referring to? And what is the background of your question?
I do not see a usecase of the SMA EV Charger (SEC) without the Sunny Home Manager (SHM) because they are closely intertwined.
The SHM provides the grid measurement data (which the SEC displays in its WebUI) to the SEC via the SMA Energy Meter protocol while the SEC probably provides the current charging power to the SHM via the SEMP protocol (Simple Energy Management Protocol). If there are additional/new protocols between SEC and SHM I do not know. SMA has not disclosed such protocol - if it exists at all - by which the SEC provides additional data to the SHM. If you get to know anything, you are welcome to share it with us.
Also the SMA EV Charger does not support modbus access. 
So the answer in short is No. I do not see a possible way to get data from the SEC directly (except via the SEMP protocol, but this is rather limited to the charging control data and would imply that you implement your own Energy Manager) . The grid data is available only from the SHM anyway.

**Comment by lolax80** [comment]
I want see the kWh, the actually states of loading ... from the ev charger in my iobroker

**Comment by pdbjjens** [comment]
@lolax80 
Understood. But as I already pointed out, I currently see no possible way to get the data you are asking for from the SEC until SMA discloses a SEC interface protocol. 
Maybe you should ask your question in the [iobroker forum](https://forum.iobroker.net/topic/1100/sma-wechselrichter). 
Perhaps somebody in the community knows more.
