### ISSUE TITLE
Please add to stable repository if adapter is working for users

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.sma-em#18]

**Comment by DutchmanNL** [comment]
waiting for feedback next 2 weeks

**Comment by mcm1957** [comment]
According to Telegram you maintain this adapter. I do not see any bigger problems recorded as issues. 
So could you check if anything prohibits a release to stable? 

The adapter is currently only available at latest, but I do not see any reason to keep it away from stable.

**Comment by pdbjjens** [comment]
@mcm1957  @DutchmanNL 
It is my intention to release it to stable asap. Since I just released a minor version with a new feature two weeks ago, I would like to keep it in latest for some time to wait for user issues and forum user feedback. Up to now there are no serious complaints however.
Also there is still issue #15 pending. I do not see the neccessity for auto-discovery since the adapter automatically discovers all devices on startup. But I do not know who can decide whether it is o.k. to release to stable without auto-discovery.
If I were to decide, I would close #15 with above comment.

**Comment by mcm1957** [comment]
Its OK to wait some time - did not realized that you just released a new version. Please keep it in mind as the automatic checker does not remind as long as no stable version exists.

Autodiscovery is definitly no problem for stable. Only (major) bug issues should be fixed befor an adapter is released to stable. Any feature request can be kept open (otehrwise some adapters would never go to stable :-) )

Please discuss with @Apollon77 whether adding this adapter to autodiscovery is desired. But note that auto-discovery is a feature to suggest the installation of this adapter if a matching device exists in network. It cannot be replaced by any detection inside the adapter - those features are disjunct in my oppinion. If it is possible to detect a matching device i.e. by testing for a specific port or a simple reaction, autodetection should be considered to be implemented. So I would keep #15 open until discussed with Apollon.

**Comment by mobifu1** [comment]
can you give an update about the stable state?

**Comment by pdbjjens** [comment]
@mobifu1 
For the current v0.7.0 there is one issue fixed ([Detect SMA EM1.0 SUSy 270]) and one pending (#552 ). As soon as I can close #552 I will prepare a new minor latest release which after due time - if no new serious bugs show up - will be moved to stable.

**Comment by mcm1957** [comment]
Thanks for the update

**Comment by mcm1957** [comment]
issue outdated and replaced by #577
