### ISSUE TITLE
Sunny Home Manager not found

### ISSUE THREAD

**Issue by stevoboy** [iobroker-community-adapters/ioBroker.sma-em#274]
**Describe the bug**  
I set up the adapter with following parameters:
![image](https://user-images.githubusercontent.com/84937873/137597976-c38e649e-89fb-4a77-a461-6c6a33ef6d7d.png)

The adapter does not find our installed Sunny Home Manager 2.0:
![image](https://user-images.githubusercontent.com/84937873/137597992-a2f43859-6020-44a0-b161-1e431122e4a8.png)

**To Reproduce**  
1. Install adapter and run instance with default settings.

**Expected behavior**  
SHM 2.0 should be found on IP 192.168.178.37. Objects should be added and filled with readout of the SHM.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/84937873/137598061-f5fc81b6-759b-4ef4-b6e2-fe7a5a63bd37.png)

I assume that I might need to activate some kind of API in the settings of the Sunny Home Manager?

**Comment by pdbjjens** [comment]
@stevoboy 
This problem typically shows up, when the SHM is not in the same subnet as the iobroker server. Thus the multicasts of the SHM do not reach the sma-em adapter. It is not necessary to make any config to the SHM. It generally multicasts its data right from the start. Rather you should check your network configuration. Multicasts are not generally forwarded by routers between subnets. Also some switches interfere with the multicasts. That is why SMA recommends to switch off IGMP V3 snooping. But I assume your problem roots in a router problem since from your report above I saw that your iobroker is in subnet 172.19.0.2 while the SHM is in 192.168.178.37 . I suggest that you look whether your router supports multicast forwarding and configure it accordingly. If this does not work I propose that you describe your problem in the iobroker forum e.g. [https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-6-x-latest](https://forum.iobroker.net/topic/43011/test-adapter-sma-em-v0-6-x-latest) 
Maybe some other user can help.

**Comment by stevoboy** [comment]
I realized one thing last night, if the adapter is listening on port 9522, I must open a port in the docker container as well. I did that now:
![image](https://user-images.githubusercontent.com/84937873/137851559-28bfd2d0-0b17-4b94-94ff-aa071ee0e881.png)
Shouldnt the IP address not be found now when I ping it?
![image](https://user-images.githubusercontent.com/84937873/137851622-3bf3ee4c-bcdd-4dcc-a313-0c20e6077c81.png)

**Comment by pdbjjens** [comment]
@stevoboy 
It seems that SMA multicast with docker containers is a general problem.
[https://forum.iobroker.net/topic/38520/multicast-sma-em-usg-netztrennung](https://forum.iobroker.net/topic/38520/multicast-sma-em-usg-netztrennung)
In [https://smarthome.buanet.de/2019/05/iobroker-unter-docker-auf-der-synology-diskstation-v3/](https://smarthome.buanet.de/2019/05/iobroker-unter-docker-auf-der-synology-diskstation-v3/) 
it is clearly stated that the simple docker network bridged mode will not work for adapters which use multicast.
A solution seems to be to configure the docker network to use macvlan. A description can be found [https://smarthome.buanet.de/2020/09/macvlan-ueber-portainer-einrichten/](https://smarthome.buanet.de/2020/09/macvlan-ueber-portainer-einrichten/)

**Comment by pdbjjens** [comment]
@stevoboy 
Have you been able to solve your problem meanwhile? Please indicate whether I can close this issue

**Comment by stevoboy** [comment]
Yes, I solved the problem by reinstalling the docker container in host mode.
