### ISSUE TITLE
Warning in log following latest HM FW Update

### ISSUE THREAD

**Issue by ck-coke** [iobroker-community-adapters/ioBroker.sma-em#285]
Since the latest Update of the FW on the HM there are several warning messages in the log:
The adapter itself still seems to work but is there an update possible to avoid these repeated log entries?

![grafik](https://user-images.githubusercontent.com/77073548/139924251-6021ddc6-344d-49f7-bfea-b48e14cb6194.png)

**Comment by pdbjjens** [comment]
@ck-coke 
Please let us know the firmware version of the SHM and also the version of the sma-em adapter which you are using. Also please specify the iobroker host and nodejs versions. Also a log file of a restart of the sma-em adapter would be helpful.

**Comment by ricott** [comment]
I don't use ioBroker myself, but since I have an app for Homey that also is written in nodejs I keep a tap on what is going here 😀

Seems like firmware version 2.07.5.R came with a new type of UDP message. I see this in my Homey app and also in a script I use for my Victron Cerbo. The new message is much shorter, but the start of the message including the serial is the same.

@pdbjjens, do you have access to any documentation on what this new type of message could be?

Old type that is still generated and works as before
`534d4100000402a000000001024c001060690174b32dd9353781c06e00010400000000a8000108000000001c5afe19080002040000000000000208000000000b36ded708000304000000000000030800000000059fdb8680000404000000104400040800000000057038d9780009040000001047000908000000001f0d15fa78000a040000000000000a08000000000c33131e08000d040000000028000e04000000c32e001504000000000a001508000000000992b7688000160400000000000016080000000003eb8ea9d80017040000000000001708000000000199aad9e000180400000004c1001808000000000210736740001d0400000004c1001d08000000000a7c98d088001e040000000000001e08000000000440a2b680001f04000000032000200400000388aa002104000000000800290400000000a500290800000000094c354710002a040000000000002a080000000003a353b4d8002b040000000000002b080000000001a59084f8002c04000000083c002c080000000002d027bcd00031040000000842003108000000000a9d5e6a08003204000000000000320800000000042132172800330400000004580034040000039721003504000000004e003d040000000000003d08000000000a0b411210003e040000000006003e080000000004372c1f88003f040000000000003f080000000002b7e5913800400400000003480040080000000000e6e31ef80045040000000000004508000000000af57a9388004604000000034800460800000000047dbd5d90004704000000028d00480400000392380049040000000007900000000207055200000000`

New type of message (don't know with what frequency this is sent yet, but seems less frequent than than the old message)
`534d4100000402a00000000100260010606509a0ffffffffffff0000740135d92db3000000000000b3ac00020000000000000000000000000000`

**Comment by pdbjjens** [comment]
@ricott 
This message belongs to a different SMA protocol (the protocol-id for the SMA-EM-protocol is 0x6069 while the protocol-id in the message you saw has a protocol-id 0x6065). In our SMA-EM Adapter we simply ignore all protocol elements other than 0x6069, for instance also the protocol-id 0x0001 for the device discovery protocol. Which protocol has protocol-id 0x6065 I don't know. Maybe SEMP? (Do you have any device in your system which speaks via SEMP to the SHM. e.g. a heatpump or a EV-Charger?)

**Comment by ricott** [comment]
Thanks @pdbjjens!
Guess I was a bit stressed, the "new" message type isn't even with the same serial as the first one. Not sure how I missed that. Added filtering on the protocol id 6069 👍

**Comment by pdbjjens** [comment]
@ck-coke 
The problem you mentioned should be fixed at least since  version  v0.6.4 . If you still have the problem and have not done so yet, then please update to this version.

**Comment by ck-coke** [comment]
> @ck-coke The problem you mentioned should be fixed at least since version v0.6.4 . If you still have the problem and have not done so yet, then please update to this version.

Confirmed solved. Thanks a lot!
