### ISSUE TITLE
Get consumer info

### ISSUE THREAD

**Issue by freizeitbastler** [iobroker-community-adapters/ioBroker.sma-em#327]
In the iOS app i have the information about the consumption of consumers. eg. my heat pump is listed as non-controllable consumer with consumption in Watt. Is there any chance to get thin information into ioBroker?

**Comment by pdbjjens** [comment]
@freizeitbastler 
Unfortunately this is not technically possible with the sma-em adapter because the data retrieved from the SHM or SMA-EM does not include consumption info on specific devices. Only the sum of all consumers is available. 
SMA is able to separate consumption data for devices like heat pumps, household appliances or smart switches which are managed via the SHM using protocols like SEMP or EEBus and transfers this info to the Sunny Portal from where it is accessible to the SMA app. The transfer protocol is not disclosed by SMA so that the data is not available to iobroker. I am not aware of any iobroker adapter which currently is able to read data from the Sunny Portal.
