### ISSUE TITLE
Objects "last_message" and "timetick" do not update anymore since update to 0.7

### ISSUE THREAD

**Issue by wavey93** [iobroker-community-adapters/ioBroker.sma-em#593]
Since update to 0.7, the Objects "last_message" and "timetick" do not update anymore. Debug log does not show any issue. Other Objects are being updated as expected.

New install of adapter did not help. Can i support somehow?

Thanks!

**Comment by pdbjjens** [comment]
@wavey93 
These values have been removed from the adapter completely since they generate an excessive load on the iobroker.
If some info regarding when a value was last received and/or updated, it can be read from the timestamps of the objects's state values.
I recommend that you stop the adapter, delete the object tree completely and restart the adapter. Then the objects "last_message" and "timetick" should be gone.

**Comment by pdbjjens** [comment]
Intended behaviour. Will not be changed.

**Comment by mcm1957** [comment]
If the objects got obsolete  i would suggestctobdelete them by code.

Deleting rhe complete tree might have sideeffects like loosing custom setup (history i.e)

**Comment by pdbjjens** [comment]
@mcm1957 
In this case, it might suffice to delete just the questionable objects from the tree manually.  Since this happen just once at the update to > 0.7.0 I don't think it is worthwhile to implement extra code for this.

**Comment by mcm1957** [comment]
OK, Its not much code, but its your decision and OK for me.

But think about adding a note to the README / releasenotes section to do this (and how) so that at least some error issues can be avoided.

**Comment by pdbjjens** [comment]
@mcm1957 
Yes, you are right, it is not much code. But it occurred to me that silently deleting these states might also confuse some users - although I believe that no one ever used these datapoints in any script. So currently I think I will add some text to the readme as you proposed.

**Comment by mcm1957** [comment]
That's totally ok for me

**Comment by pdbjjens** [comment]
Added info in Release notes of v1.0.0
