### ISSUE TITLE
enhancement: Extend Adapter for simulating SMA eMeter

### ISSUE THREAD

**Issue by bastian-mer** [iobroker-community-adapters/ioBroker.sma-em#739]
SMA Inverter are often used in setups, where some kind of a smart meter is already installed and used with iobroker. Installing an additional sma HomeManager so feed power mesurement into SMA inverters would be a mess of some hundrets of euros. It would be great, if this adapter would not only be able to read the udp multicast of an sma emeter 20 but also to be able to simulate one with values given over iobroker states to bring this data into an sma inverter.
A little C++-Programm that simulates an sma emeter with fixed hardcoded values that gets recogniced correctly by an sma sunny tripower can be found here: https://github.com/RalfOGit/sma-emeter-simulator

**Comment by bastian-mer** [comment]
If anybody is willing to start developing this feature i can help testing fur sure.

**Comment by pdbjjens** [comment]
@mcm1957 @bastian-mer 
This looks like an interesting proposal. In addition to simulating an SMA Emeter in case that only a different Emeter is available  I imagine that such functionality might be useful also for testing the sma-em adapter or other SMA adapters.

However, I think that this functionality should **not** be added to the current sma-em adapter but rather be implemented in a separate SMA-EM-Emulator adapter. 
Why? 
1. The addition of the emulator code would clutter and destabilize the sma-em code.
2. Code overlap would probably be marginal
3. Network configuration for multicast of sender und receiver in the same adapter process might be demanding if not impossible (I have not looked into this yet)
4. 99% of the sma-em users would not need this functionality
5. Configuration of the adapter would become much more complicated and too confusing for users and therefore require much more support in the forum or here.
6. Having a separate emuator adapter would faciltate testing of sma-em and other SMA adapters

Since I currently do not have time to implement a new SMA-EM-Emulator adapter, I propose to move this to the Adapter Requests List https://github.com/ioBroker/AdapterRequests. Maybe someone in the community is interested.

**Comment by mcm1957** [comment]
OK, arguments to split this into an extra adapter seem plausible. 
Fell free to close here and either of you to create an adapter request issue.

I do not want to assume any chances for implemnattion as the list of adapterREqeusts is rutehr long. Most likelyan implementaion will only occure if a dev has personall interest in this. If YOU want to implement such an adapter, feel free to contact us at telegram (adapter-development-starters) - invite Links available at https://iobroker.dev. We will help to get started for sure.
